"""
📊 SIGNAL - Signal Data Model
Defines the Signal dataclass used by the V2 pipeline.

Author: galinborisov10-art
Version: 2.0
"""

from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from datetime import datetime, timezone
from enum import Enum


class SignalDirection(Enum):
    """Signal direction"""
    LONG = "LONG"
    SHORT = "SHORT"


class SignalStrength(Enum):
    """Signal strength levels"""
    WEAK = "WEAK"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"
    EXTREME = "EXTREME"


class SignalStatus(Enum):
    """Signal lifecycle status"""
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    TRIGGERED = "TRIGGERED"
    HIT_TP = "HIT_TP"
    HIT_SL = "HIT_SL"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"


@dataclass
class Signal:
    """
    Signal Data Model

    Represents a complete trading signal generated by the V2 pipeline,
    including entry, SL, TP levels and confidence scoring.

    Attributes:
        signal_id: Unique identifier for the signal
        symbol: Trading pair (e.g. 'BTC/USDT')
        timeframe: Chart timeframe (e.g. '1H', '4H')
        direction: LONG or SHORT
        entry_price: Optimal entry price
        entry_zone_low: Lower bound of entry zone
        entry_zone_high: Upper bound of entry zone
        stop_loss: Stop loss price
        take_profit_1: First take profit level (1:1 RR)
        take_profit_2: Second take profit level (1:2 RR)
        take_profit_3: Third take profit level (1:3 RR)
        confidence: Overall confidence score (0-100)
        strength: Signal strength label
        status: Current lifecycle status
        created_at: Signal creation timestamp
        components: List of component names that contributed
        htf_bias: Higher timeframe bias ('BULLISH'/'BEARISH'/'RANGING')
        anchor_level: Key anchor price used for analysis
        risk_reward_ratio: Calculated RR ratio
        notes: Additional context / narrative
        raw_data: Raw analysis data dict for debugging
    """
    signal_id: str
    symbol: str
    timeframe: str
    direction: SignalDirection
    entry_price: float
    entry_zone_low: float
    entry_zone_high: float
    stop_loss: float
    take_profit_1: float
    take_profit_2: float
    take_profit_3: float
    confidence: float
    strength: SignalStrength
    status: SignalStatus = SignalStatus.PENDING
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    components: List[str] = field(default_factory=list)
    htf_bias: str = "UNKNOWN"
    anchor_level: Optional[float] = None
    risk_reward_ratio: float = 0.0
    notes: str = ""
    raw_data: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize signal to dictionary"""
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "direction": self.direction.value,
            "entry_price": self.entry_price,
            "entry_zone_low": self.entry_zone_low,
            "entry_zone_high": self.entry_zone_high,
            "stop_loss": self.stop_loss,
            "take_profit_1": self.take_profit_1,
            "take_profit_2": self.take_profit_2,
            "take_profit_3": self.take_profit_3,
            "confidence": self.confidence,
            "strength": self.strength.value,
            "status": self.status.value,
            "created_at": self.created_at.isoformat(),
            "components": self.components,
            "htf_bias": self.htf_bias,
            "anchor_level": self.anchor_level,
            "risk_reward_ratio": self.risk_reward_ratio,
            "notes": self.notes,
        }

    @property
    def sl_pips(self) -> float:
        """Distance from entry to stop loss"""
        return abs(self.entry_price - self.stop_loss)

    @property
    def tp1_pips(self) -> float:
        """Distance from entry to TP1"""
        return abs(self.take_profit_1 - self.entry_price)

    @property
    def is_valid(self) -> bool:
        """Basic validity check"""
        if self.entry_price <= 0 or self.stop_loss <= 0:
            return False
        if self.direction == SignalDirection.LONG:
            return self.stop_loss < self.entry_price < self.take_profit_1
        else:
            return self.stop_loss > self.entry_price > self.take_profit_1


# Backward-compatibility alias
SignalV2 = Signal
